classes/TaxonProfile.php, taxa/index.php
- Adding ability to display info for a non-accepted taxon that is linked to more than one accepted names
=> Taxon Profile dev

checklists/checklist.php, checklists/checklistadmin.php, checklists/dynamicmap.php, checklists/rpc/index.php, checklists/tools/checklistloader.php, checklists/tools/index.php, checklists/voucheradmin.php, sitemap.php
- Remapped header.php file within  includes directory
- Remapped footer.php file within  includes directory
=> Checklist dir modifications needed for new framework

classes/ChecklistManager.php, classes/DwcArchiverCore.php, classes/DwcArchiverOccurrence.php, classes/OccurrenceAttributes.php, classes/OccurrenceEditorServices.php, classes/ProfileManager.php, classes/SpecProcNlpSalix.php, classes/SpecUploadBase.php, classes/TPDescEditorManager.php, classes/TaxonProfile.php, classes/TaxonSearchSupport.php, classes/TaxonomyDisplayManager.php, classes/TaxonomyHarvester.php, classes/TaxonomyUpload.php, collections/traitattr/attributemining.php, config/schema-1.0/dev/db_schema_patch_pending.sql, config/symbbase.php, css/quicksearch.css, css/symb/speciesprofile.css, includes/head_template.php, js/symb/api.taxonomy.taxasuggest.js, js/symb/collections.editor.main.js, taxa/index.php, taxa/profile/tpeditor.php, taxa/profile/tpimageeditor.php, themes/liquid/css/main.css, themes/static/css/main.css
- Data cleaning data check set to be more dynamic based on current date
=> Data harvesting bug

classes/OccurrenceAttributes.php, classes/OccurrenceCollectionProfile.php, collections/traitattr/occurattributes.php
- Fix to Occurrence Attribute "skip" function
- Fix filter by country/state within Occurrence Trait image coding tool
- Collection profile display adjsutment to only display an IPT endpoint once when used multiple times within a complex import profile
=> Various code fixes

classes/OccurrenceUtilities.php
- Additional improvement on eventDate parsing during data import
=> Occurrence Import adjsutments

classes/SpecUploadDwca.php
- Minor adjustment to importing via SSL
=> DwC-A Occurrence Harvesting adjustment

classes/ImageLibrarySearch.php, classes/OccurrenceSearchSupport.php, imagelib/search.php
- Enhansed variable sanitation
- Additional adjustments on debugging to previous submission
=> Image Search Dev

collections/reports/labelmanager.php, collections/reports/labelsword.php
- Debug php request terms to match adjsuted form elements
- Debug javascript to match form elements
=> Occurrence Label Module

classes/OccurrenceIndividual.php, collections/individual/index.php
- Adjustment to display of trait/state terms to better represent true/false trait types
=> Occurrence Detail Trait debugging

classes/OccurrenceAttributeSearch.php
- Changed all to checkboxes so that one can search on any combination of trait codings
- Skip numeric traits as a search option since they are still in development
=> Occurrence Trait Search Developments

classes/OccurrenceLabel.php
- Allow users to print labels outside of their user profile from within a Research Observation project
=> Label Developments

collections/editor/occurrenceeditor.php, collections/tools/mappolyaid.php
- Force refresh of js
- Make polygon default tool within mappolygon
=> Occurrence Editor minor adjustments

checklists/checklist.php, checklists/checklistadmin.php, checklists/checklistadminmeta.php, checklists/index.php, classes/ImInventories.php
- Bug fix interfering with parent/child assignment of an exclusion checklist
- Input variable sanitation and prepared statement security updates
=> Checklist management Dev

classes/DwcArchiverCore.php
- Custom downloads only applied single conditions
=> Occurrence Custom Download bug

classes/ProfileManager.php, docs/INSTALL.md, docs/UPDATE.md, profile/index.php, profile/newprofile.php, profile/viewprofile.php
- User Management revamp
- Update installation and update docs
=> Symbiota 3.0 production push

checklists/clsppeditor.php, checklists/nonvoucheredtab.php, checklists/voucheradmin.php, classes/ChecklistManager.php, classes/ChecklistVoucherAdmin.php, classes/ChecklistVoucherManager.php, classes/ChecklistVoucherReport.php, classes/DwcArchiverAttribute.php, classes/DwcArchiverCore.php, classes/DwcArchiverImage.php, classes/DwcArchiverOccurrence.php, classes/OccurrenceDownload.php, classes/OccurrenceEditorManager.php, classes/OccurrenceEditorResource.php, classes/OccurrenceIndividual.php, classes/OccurrenceManager.php, classes/PluginsManager.php, classes/RpcOccurrenceEditor.php, collections/editor/rpc/deleteIdentifier.php, collections/editor/rpc/getassocvouchers.php, collections/individual/index.php, collections/individual/linkedresources.php, config/schema/1.0/patches/db_schema_patch-3.0.sql, config/schema/3.0/db_schema-3.0.sql, profile/viewprofile.php
- Schema adjustments
- Checklist/voucher management dev
=> Symbiota 3.0 rollout adjustments

classes/ImageProcessor.php, classes/OccurrenceEditorImages.php, classes/OccurrenceSearchSupport.php, classes/SpecUploadBase.php, classes/TaxonomyHarvester.php, config/symbbase.php
* Occurrence Upload adjustment - Trim off delimiters that are left on the beginning or end of filter string to ensure that null values are not included
* Collection Listing bug fix - Collection categories failing to be persist
* Occurrence Image Submissions issue resolution - Set default image sort order to 40 for observations to ensure that preserved specimen images do not take precedence
* Image Processing bug - collection identifier (collid) failed to be passed to statistics update function
* Resolve Taxonomy Harvester issues - Improve TROPICOS method of matching on infraspecific taxa - Improve close match suggestions
Pull Request Checklist:
Thanks for contributing and keeping it clean!
=> Hotfix 2023 06 03 (#508)

classes/ImageLocalProcessor.php, classes/TaxonomyCleaner.php, classes/TaxonomyHarvester.php, collections/specprocessor/processor.php, collections/specprocessor/standalone_scripts/ImageBatchHandler.php
- Provide support for input file to include medium and thumbnail image derivatives
- Expand Image Map processing to allow mapping file to include any images table field name
- Expand images insert function to handle any valid field found within images table
- Merge duplicate actions into shared private functions
- MD5 hash large version of image input file
- Taxonomy harvesting adjustments associated with hotfix 2023-06-19
=> Refactor ImageLocalProcessor

classes/ImageLocalProcessor.php
- Enforce default action of accepting derivative urls supplied within a csv image map file
- Improve uriExists function
- Make sure to remove staging images
- Misc bugs
=> Image Import Processing bug fixes

classes/ImageLocalProcessor.php
- md5 hash large version of image
- Don't generate md5 hash if supplied by source, and image is not modified
- Suppress warnings when image derivatives are unlinked
=> Image Processing adjustments

collections/editor/includes/resourcetab.php, content/lang/collections/admin/importextended.en.php, content/lang/collections/associations.en.php, content/lang/collections/associations.es.php, content/lang/collections/associations.fr.php, content/lang/collections/editor/includes/resourcetab.en.php, content/lang/collections/editor/includes/resourcetab.es.php, content/lang/collections/editor/includes/resourcetab.fr.php
* Associations Management dev
- Fix Associations Type to a set list within occurrence editor
- Unify international language files
- Internalize additional terms
- 508 compliance issue
=> Associations management 2023 11 (#740)

collections/search/index.php
Update from BioKIC/Developement
=> invoke jquery-ui in the head instead of the body (#1273)

css/v202209/symbiota/variables.css, includes/head.php, includes/header.php
=> Styling changes for readability
